// Regenerates the bundled ESPN snapshot under src/data/ (leagueTeams.ts,
// myTeam.ts, freeAgents.ts) from ESPN's live roster API.
//
// Why this exists: the app's "Refresh from ESPN" button only ever updates
// lineup *slots* for players already present in the bundled snapshot (see
// syncRosterFromEspn in src/hooks/useFantasyApp.ts + assignFromSlots in
// src/lib/teamRoster.ts, which both walk the bundled roster array rather than
// ESPN's live one) -- it can never add a player who wasn't already in that
// array, or drop one who no longer is. So a waiver add/drop, a streamed
// D/ST, or a trade made in the ESPN app silently never shows up anywhere in
// this app until the bundled data itself is regenerated. Run this script
// after any such roster move.
//
// Usage: npm run sync:snapshot
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { LEAGUE_CONFIG } from "../src/config/league.js";
import { ALL_TEAMS } from "../src/data/allTeams.js";
import { FREE_AGENTS } from "../src/data/freeAgents.js";
import { syncLiveRosters } from "../src/lib/espnLeague.js";
import type { LeagueTeam, Player, RosterPlayer } from "../src/types.js";

const DATA_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "../src/data");

// Seed ESPN's live response with what we already know (mainly so `tier`,
// which ESPN doesn't expose directly, stays continuous instead of being
// recomputed from scratch every run) -- same pattern runSenseiTurn.ts uses.
function snapshotKnownPlayers(): Player[] {
  const map = new Map<number, Player>();
  for (const t of ALL_TEAMS) for (const p of t.roster) map.set(p.id, p);
  for (const p of FREE_AGENTS) if (!map.has(p.id)) map.set(p.id, p);
  return [...map.values()];
}

function str(s: string): string {
  return JSON.stringify(s);
}

function proj(n: number): string {
  return n.toFixed(1);
}

// Field order matches the hand-written literals already in leagueTeams.ts.
function rosterPlayerLiteral(p: RosterPlayer): string {
  return (
    `{ id: ${p.id}, name: ${str(p.name)}, pos: ${str(p.pos)}, team: ${str(p.team)}, ` +
    `proj: ${proj(p.proj)}, tier: ${p.tier}, status: ${str(p.status)}, bye: ${p.bye}, ` +
    `starter: ${p.starter}, slot: ${str(p.slot)} }`
  );
}

// Field order matches myTeam.ts / freeAgents.ts (bye before proj there).
function flatPlayerLiteral(p: Player): string {
  return (
    `{ id: ${p.id}, name: ${str(p.name)}, pos: ${str(p.pos)}, team: ${str(p.team)}, ` +
    `bye: ${p.bye}, proj: ${proj(p.proj)}, tier: ${p.tier}, status: ${str(p.status)} }`
  );
}

function renderLeagueTeams(teams: LeagueTeam[], syncedAt: string): string {
  const teamBlocks = teams
    .map((t) => {
      const players = t.roster.map((p) => `    ${rosterPlayerLiteral(p)},`).join("\n");
      return `  { id: ${t.id}, name: ${str(t.name)}, owner: ${str(t.owner)}, roster: [\n${players}\n  ]},`;
    })
    .join("\n");

  return `import type { LeagueTeam } from "../types.js";

// Real league rosters (12-team "Ten Idiots League", ESPN league 973201555).
// "starter"/"slot" reflect each manager's ACTUAL lineup (ESPN's own
// lineupSlotId), not a reconstruction -- this is really who they're starting.
//
// Auto-generated by \`npm run sync:snapshot\` (scripts/syncLeagueSnapshot.ts)
// from ESPN's live roster API -- do not hand-edit; re-run the script instead
// after any waiver add/drop or trade, or this drifts from reality again.
// Last synced: ${syncedAt}.
export const LEAGUE_TEAMS: LeagueTeam[] = [
${teamBlocks}
];

// Flat array of every rostered player across the league, tagged with their
// fantasy team, for use in the Trade Analyzer opponent-side picker.
export const ALL_LEAGUE_PLAYERS = LEAGUE_TEAMS.flatMap((t) =>
  t.roster.map((p) => ({ ...p, fantasyTeamId: t.id, fantasyTeamName: t.name }))
);
`;
}

function renderMyTeam(myTeam: LeagueTeam, syncedAt: string): string {
  const players = myTeam.roster
    .map((p) => `  ${flatPlayerLiteral(p)},`)
    .join("\n");

  const lineupEntries = myTeam.roster
    .filter((p) => p.starter && p.slot !== "BE" && p.slot !== "IR")
    .map((p) => {
      const key = p.id < 0 ? `[${p.id}]` : `${p.id}`;
      return `  ${key}: ${str(p.slot)}, // ${p.name}`;
    })
    .join("\n");

  return `import type { LeagueTeam, Player } from "../types.js";
import { LEAGUE_CONFIG } from "../config/league.js";

// Your real 2026 roster (Ten Idiots League, ESPN league 973201555).
// Pulled live from the ESPN Fantasy API (Week 1 projections, actual PPR scoring rules).
// "tier" is derived locally from each player's ESPN ownership % (>=80 tier 1, >=40 tier
// 2, else tier 3) -- ESPN doesn't expose a tier field directly.
//
// Auto-generated by \`npm run sync:snapshot\` (scripts/syncLeagueSnapshot.ts) --
// do not hand-edit; re-run the script instead after any waiver add/drop or
// trade. Last synced: ${syncedAt}.
export const MY_TEAM_PLAYERS: Player[] = [
${players}
];

// Which ESPN lineup slot each of your players was starting in, so your team
// can be treated as just another LeagueTeam (same shape as every opponent in
// leagueTeams.ts). Anyone not listed here is on the bench.
const MY_TEAM_LINEUP: Record<number, string> = {
${lineupEntries}
};

// Your team as a full LeagueTeam entry, so the app can select it or any
// opponent interchangeably as "the team you're managing". \`id\` must match
// ESPN's own numeric team id (not just be unique locally) -- syncRosterFromEspn
// in useFantasyApp looks up this id in the live ESPN lineup response, so a
// mismatch here means your team silently never picks up live ESPN changes.
export const MY_TEAM: LeagueTeam = {
  id: LEAGUE_CONFIG.myTeamId,
  name: LEAGUE_CONFIG.myTeamName,
  owner: LEAGUE_CONFIG.myOwnerName,
  roster: MY_TEAM_PLAYERS.map((p) => {
    const slot = MY_TEAM_LINEUP[p.id] ?? "BE";
    return { ...p, starter: slot !== "BE", slot };
  }),
};
`;
}

function renderFreeAgents(agents: Player[], syncedAt: string): string {
  const players = agents.map((p) => `  ${flatPlayerLiteral(p)},`).join("\n");

  return `import type { Player } from "../types.js";

// Bundled fallback only -- a point-in-time export of who was unrostered when
// this file was last regenerated. The app no longer treats this as the real
// free-agent pool: useFantasyApp fetches the live pool from ESPN
// (fetchLiveFreeAgents in lib/espnLeague.ts) on load and on "Refresh from
// ESPN", and only falls back to this static list if that live fetch fails
// (e.g. offline). Don't hand-edit this expecting it to reflect current
// waiver-wire reality.
//
// Auto-generated by \`npm run sync:snapshot\` (scripts/syncLeagueSnapshot.ts).
// Last synced: ${syncedAt}.
export const FREE_AGENTS: Player[] = [
${players}
];
`;
}

async function main() {
  console.log(`Syncing live ESPN snapshot for league ${LEAGUE_CONFIG.espnLeagueId}...`);
  const snapshot = await syncLiveRosters(snapshotKnownPlayers());
  const syncedAt = new Date(snapshot.fetchedAt).toISOString();

  const myTeam = snapshot.teams.find((t) => t.id === LEAGUE_CONFIG.myTeamId);
  if (!myTeam) {
    throw new Error(
      `LEAGUE_CONFIG.myTeamId (${LEAGUE_CONFIG.myTeamId}) wasn't found among the ${snapshot.teams.length} teams ESPN returned -- check config/league.ts.`
    );
  }
  const opponents = snapshot.teams
    .filter((t) => t.id !== LEAGUE_CONFIG.myTeamId)
    .sort((a, b) => a.id - b.id);

  writeFileSync(path.join(DATA_DIR, "leagueTeams.ts"), renderLeagueTeams(opponents, syncedAt));
  writeFileSync(path.join(DATA_DIR, "myTeam.ts"), renderMyTeam(myTeam, syncedAt));
  writeFileSync(path.join(DATA_DIR, "freeAgents.ts"), renderFreeAgents(snapshot.freeAgents, syncedAt));

  console.log(
    `Wrote ${opponents.length} opponent rosters, your ${myTeam.roster.length}-player roster, and ${snapshot.freeAgents.length} free agents.`
  );
  console.log("Review the diff (git diff src/data) before committing.");
}

main().catch((err) => {
  console.error("sync:snapshot failed:", err);
  process.exitCode = 1;
});
