import type { LeagueTeam, Player } from "../types.js";
import { LEAGUE_CONFIG } from "../config/league.js";

// Your real 2026 roster (Ten Idiots League, ESPN league 973201555).
// Pulled live from the ESPN Fantasy API (Week 1 projections, actual PPR scoring rules).
// "tier" is derived locally from each player's ESPN ownership % (>=80 tier 1, >=40 tier
// 2, else tier 3) -- ESPN doesn't expose a tier field directly.
//
// Auto-generated by `npm run sync:snapshot` (scripts/syncLeagueSnapshot.ts) --
// do not hand-edit; re-run the script instead after any waiver add/drop or
// trade. Last synced: 2026-09-25T12:07:31.971Z.
export const MY_TEAM_PLAYERS: Player[] = [
  { id: 4426515, name: "Puka Nacua", pos: "WR", team: "LAR", bye: 11, proj: 0.0, tier: 1, status: "Questionable" },
  { id: 4432665, name: "Brock Bowers", pos: "TE", team: "LV", bye: 13, proj: 13.7, tier: 1, status: "Questionable" },
  { id: 4427366, name: "Breece Hall", pos: "RB", team: "NYJ", bye: 13, proj: 15.0, tier: 1, status: "Healthy" },
  { id: 4372016, name: "Jaylen Waddle", pos: "WR", team: "DEN", bye: 10, proj: 12.4, tier: 1, status: "Healthy" },
  { id: 3915416, name: "DJ Moore", pos: "WR", team: "BUF", bye: 7, proj: 11.7, tier: 1, status: "Questionable" },
  { id: 4432710, name: "TreVeyon Henderson", pos: "RB", team: "NE", bye: 11, proj: 10.0, tier: 1, status: "Healthy" },
  { id: 4360761, name: "Michael Wilson", pos: "WR", team: "ARI", bye: 14, proj: 10.5, tier: 1, status: "Healthy" },
  { id: 12483, name: "Matthew Stafford", pos: "QB", team: "LAR", bye: 11, proj: 15.6, tier: 1, status: "Healthy" },
  { id: 4241416, name: "Chuba Hubbard", pos: "RB", team: "CAR", bye: 5, proj: 15.5, tier: 1, status: "Healthy" },
  { id: 4360569, name: "Jordan Mason", pos: "RB", team: "MIN", bye: 6, proj: 0.0, tier: 2, status: "IR" },
  { id: 2976212, name: "Stefon Diggs", pos: "WR", team: "WSH", bye: 7, proj: 9.4, tier: 1, status: "Healthy" },
  { id: -16007, name: "Broncos D/ST", pos: "DST", team: "DEN", bye: 10, proj: 3.8, tier: 1, status: "Healthy" },
  { id: 4686361, name: "Cam Little", pos: "K", team: "JAX", bye: 7, proj: 8.7, tier: 1, status: "Healthy" },
  { id: 3929645, name: "Juwan Johnson", pos: "TE", team: "NO", bye: 8, proj: 8.5, tier: 2, status: "Healthy" },
  { id: -16025, name: "49ers D/ST", pos: "DST", team: "SF", bye: 8, proj: 7.5, tier: 2, status: "Healthy" },
  { id: 3912547, name: "Sam Darnold", pos: "QB", team: "SEA", bye: 11, proj: 15.8, tier: 3, status: "Healthy" },
  { id: 5081508, name: "Eli Heidenreich", pos: "RB", team: "PIT", bye: 9, proj: 4.4, tier: 3, status: "Healthy" },
];

// Which ESPN lineup slot each of your players was starting in, so your team
// can be treated as just another LeagueTeam (same shape as every opponent in
// leagueTeams.ts). Anyone not listed here is on the bench.
const MY_TEAM_LINEUP: Record<number, string> = {
  4426515: "FLEX", // Puka Nacua
  4432665: "TE", // Brock Bowers
  4427366: "RB", // Breece Hall
  4372016: "WR", // Jaylen Waddle
  3915416: "WR", // DJ Moore
  4241416: "RB", // Chuba Hubbard
  4686361: "K", // Cam Little
  [-16025]: "DST", // 49ers D/ST
  3912547: "QB", // Sam Darnold
};

// Your team as a full LeagueTeam entry, so the app can select it or any
// opponent interchangeably as "the team you're managing". `id` must match
// ESPN's own numeric team id (not just be unique locally) -- syncRosterFromEspn
// in useFantasyApp looks up this id in the live ESPN lineup response, so a
// mismatch here means your team silently never picks up live ESPN changes.
export const MY_TEAM: LeagueTeam = {
  id: LEAGUE_CONFIG.myTeamId,
  name: LEAGUE_CONFIG.myTeamName,
  owner: LEAGUE_CONFIG.myOwnerName,
  roster: MY_TEAM_PLAYERS.map((p) => {
    const slot = MY_TEAM_LINEUP[p.id] ?? "BE";
    return { ...p, starter: slot !== "BE", slot };
  }),
};
